name: link_app
description: Link mobile app (Android & iOS).
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - lib/data/DUR1/data.csv
    - lib/data/DUR2/data.csv
    - lib/data/DUR3/data.csv
    - lib/data/DUR4/data.csv
    - lib/data/DUR5/data.csv
    - lib/data/DUR6/data.csv
    - lib/data/DUR7/data.csv
    - lib/data/DUR8/data.csv
    #lib/data/DUR1 - 8/data.csv가 DUR n-n으로 줄어들 수 있음